apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: c2
  name: c2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: c2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: c2
    spec:
      containers:
        - args:
            - slurmd
          image: slurm-docker-cluster:e41370d
          name: c2
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/munge
              name: etc-munge
            - mountPath: /data
              name: slurm-jobdir
            - mountPath: /var/log/slurm
              name: var-log-slurm
            - mountPath: /etc/slurm/slurm.conf
              name: c2-claim3
      hostname: c2
      restartPolicy: Always
      volumes:
        - name: etc-munge
          persistentVolumeClaim:
            claimName: etc-munge
        - name: slurm-jobdir
          persistentVolumeClaim:
            claimName: slurm-jobdir
        - name: var-log-slurm
          persistentVolumeClaim:
            claimName: var-log-slurm
        - name: c2-claim3
          persistentVolumeClaim:
            claimName: c2-claim3
status: {}
