apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmd
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: c1
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmd
      app.kubernetes.io/part-of: slurm-docker-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmd
        app.kubernetes.io/part-of: slurm-docker-cluster
    spec:
      containers:
        - args:
            - slurmd
          image: ghcr.io/stackhpc/slurm-docker-cluster:d68068c
          name: c1
          ports:
            - containerPort: 6818
          resources: {}
          volumeMounts:
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
            - mountPath: /data
              name: slurm-jobdir
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          nfs:
            server: 172.20.37.208
            path: /exports/k8s-nfs
          #persistentVolumeClaim:
          #  claimName: slurm-jobdir
        - name: slurm-config-volume
          configMap:
            name: slurm-conf-configmap
status: {}
