apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: login
spec:
  ports:
    - name: "ssh"
      port: 22
      targetPort: 22
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    app.kubernetes.io/part-of: slurm-docker-cluster
status:
  loadBalancer: {}