apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: login
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: login
    app.kubernetes.io/part-of: slurm-docker-cluster
status:
  loadBalancer: {}