apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmdbd
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: slurmdbd
spec:
  ports:
    - name: "6819"
      port: 6819
      targetPort: 6819
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmdbd
    app.kubernetes.io/part-of: slurm-docker-cluster
status:
  loadBalancer: {}
