apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmdbd
  name: slurmdbd
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmdbd
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: slurmdbd
    spec:
      containers:
        - args:
            - slurmdbd
          image: ghcr.io/stackhpc/slurm-docker-cluster:e41370d
          name: slurmdbd
          ports:
            - containerPort: 6819
          resources: {}
          volumeMounts:
            - mountPath: /var/log/slurm
              name: var-log-slurm
            - mountPath: /etc/slurm/slurm.conf
              name: slurmdbd-claim2
            - mountPath: /etc/slurm/slurmdbd.conf
              name: slurmdbd-claim3
      hostname: slurmdbd
      restartPolicy: Always
      volumes:
        - name: var-log-slurm
          persistentVolumeClaim:
            claimName: var-log-slurm
        - name: slurmdbd-claim2
          persistentVolumeClaim:
            claimName: slurmdbd-claim2
        - name: slurmdbd-claim3
          persistentVolumeClaim:
            claimName: slurmdbd-claim3
status: {}
