apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: slurm
      app.kubernetes.io/component: slurmctld
      app.kubernetes.io/part-of: slurm-docker-cluster
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: slurm
        app.kubernetes.io/component: slurmctld
        app.kubernetes.io/part-of: slurm-docker-cluster
    spec:
      containers:
        - args:
            - slurmctld
          image: ghcr.io/stackhpc/slurm-docker-cluster:84e78ae
          name: slurmctld
          ports:
            - containerPort: 6817
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: slurm-jobdir
            #- mountPath: /var/log/slurm
            #  name: var-log-slurm
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
      hostname: slurmctld
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          nfs:
            server: 172.20.37.208
            path: /exports/k8s-nfs
        #- name: var-log-slurm
        #  persistentVolumeClaim:
        #    claimName: var-log-slurm
        - name: slurm-config-volume
          configMap:
            name: slurm-conf-configmap
status: {}
