apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: slurmctld
  name: slurmctld
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: slurmctld
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: slurmctld
    spec:
      containers:
        - args:
            - slurmctld
          image: ghcr.io/stackhpc/slurm-docker-cluster:d68068c
          name: slurmctld
          ports:
            - containerPort: 6817
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: slurm-jobdir
            #- mountPath: /var/log/slurm
            #  name: var-log-slurm
            - mountPath: /etc/slurm/slurm.conf
              name: slurm-config-volume
              subPath: slurm.conf
      hostname: slurmctld
      restartPolicy: Always
      volumes:
        - name: slurm-jobdir
          nfs:
            server: 172.20.37.208
            path: /exports/k8s-nfs
        #- name: var-log-slurm
        #  persistentVolumeClaim:
        #    claimName: var-log-slurm
        - name: slurm-config-volume
          configMap:
            name: slurm-conf-configmap
status: {}
