apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-generator-account
  annotations:
    "kubernetes.io/enforce-mountable-secrets": "true"
automountServiceAccountToken: True
secrets:
  - name: host-keys-secret
  