apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
    app.kubernetes.io/part-of: slurm-docker-cluster
  name: slurmctld
spec:
  ports:
    - name: "6817"
      port: 6817
      targetPort: 6817
  selector:
    app.kubernetes.io/name: slurm
    app.kubernetes.io/component: slurmctld
    app.kubernetes.io/part-of: slurm-docker-cluster
status:
  loadBalancer: {}
