slurmImage: ghcr.io/stackhpc/slurm-docker-cluster:d58f819

replicas:
  slurmd: 2
  login: 1

nfs:
  mountPath: /home
  claimName: rook-nfs-pv-claim

# Values for Slurm's database container
mySQL:
  #Database image to be used
  image: mariadb:10.10
  #Storage requested by the var-lib-mysql volume backing the database
  storage: 100Mi

# Configmap resource names
configmaps:
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

# Public key used for ssh access to the login node
# If let undefined, assumes you have run the provided publish-keys.sh script to publish your public key prior to deployment
sshPublicKey:

# Secret resource names
secrets:
  mungeKey: munge-key-secret

openOnDemand:
  #Password for default Open OnDemand user 'rocky'
  password: password
