slurmImage: ghcr.io/stackhpc/slurm-docker-cluster:d58f819

replicas:
  slurmd: 2
  login: 1

nfs:
  mountPath: /home
  claimName: rook-nfs-pv-claim

sqlImage: mariadb:10.10

databaseStorage: 100Mi

configmaps:
  slurmConf: slurm-conf-configmap
  slurmdbdConf: slurmdbd-conf-configmap
  sshdConfig: sshd-config-configmap

# If let undefined, assumes you have run publish-keys.sh to publish your public key prior to deployment
sshPublicKey:

secrets:
  databaseAuth: database-auth-secret
  mungeKey: munge-key-secret

#OOD username is rocky
openOndemand:
  password: password
